RF_ENGINE_IP_ADDRESS = ''
RF_ENGINE_IP_PORT = ''
GENERIC_GATEWAY_IP_ADDRESS = ''
GENERIC_GATEWAY_IP_PORT = ''
GENERIC_GATEWAY_PAGE_NAME = ''
CONNECTION_RETRY_INTERVAL = 60
TIMEOUT_IN_SECOND = 20
GENERIC_GATEWAY_TIMEOUT = 2
